name: learn-github-actions
run-name: ${{ github.actor }} is learning Cocotb
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Increased timeout
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog gtkwave
          pip install cocotb==1.8.0 cocotb-coverage pytest
          
      - name: Run original test
        id: original_test
        run: |
          make -C tests && mv tests/results.xml tests/orig.xml
          
      - name: Run delayed DUT test
        id: delayed_test
        run: |
          cp hdl/delayed_dut.v hdl/dut.v
          make -C tests && mv tests/results.xml tests/delayed_dut.xml
          
      - name: Upload waveforms
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: simulation-waveforms
          path: |
            tests/*.vcd
            tests/*.ghw
          
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'tests/*.xml'
          require_tests: false
          
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: tests/coverage.xml
