name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: dut test
      id: dut-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: dut test
        setup-command: "./setup.sh"
        command: make -C tests
        timeout: 3
    - name: delayed dut
      id: delayed-dut
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: delayed dut
        setup-command: "./setup_delayed.sh"
        command: make -C tests
        timeout: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DUT-TEST_RESULTS: "${{steps.dut-test.outputs.result}}"
        DELAYED-DUT_RESULTS: "${{steps.delayed-dut.outputs.result}}"
      with:
        runners: dut-test,delayed-dut


